// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: CH335F_USB_HUB

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_pl_port1;
extern lv_obj_t * ui_pl_shade_1;
extern lv_obj_t * ui_lb_port1;
extern lv_obj_t * ui_pl_port2;
extern lv_obj_t * ui_pl_shade_2;
extern lv_obj_t * ui_lb_port2;
extern lv_obj_t * ui_pl_port3;
extern lv_obj_t * ui_pl_shade_3;
extern lv_obj_t * ui_lb_port3;
extern lv_obj_t * ui_pl_port4;
extern lv_obj_t * ui_pl_shade_4;
extern lv_obj_t * ui_lb_port4;
extern lv_obj_t * ui_pl_volt;
extern lv_obj_t * ui_lb_tot_power;
extern lv_obj_t * ui_lb_volt;
// CUSTOM VARIABLES
extern lv_obj_t * uic_pl_port1;
extern lv_obj_t * uic_pl_shade_1;
extern lv_obj_t * uic_lb_port1;
extern lv_obj_t * uic_pl_port2;
extern lv_obj_t * uic_pl_shade_2;
extern lv_obj_t * uic_lb_port2;
extern lv_obj_t * uic_pl_port3;
extern lv_obj_t * uic_pl_shade_3;
extern lv_obj_t * uic_lb_port3;
extern lv_obj_t * uic_pl_port4;
extern lv_obj_t * uic_pl_shade_4;
extern lv_obj_t * uic_lb_port4;
extern lv_obj_t * uic_pl_volt;
extern lv_obj_t * uic_lb_tot_power;
extern lv_obj_t * uic_lb_volt;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

