// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: CH335F_USB_HUB

#include "../ui.h"

lv_obj_t * uic_lb_volt;
lv_obj_t * uic_lb_tot_power;
lv_obj_t * uic_pl_volt;
lv_obj_t * uic_lb_port4;
lv_obj_t * uic_pl_shade_4;
lv_obj_t * uic_pl_port4;
lv_obj_t * uic_lb_port3;
lv_obj_t * uic_pl_shade_3;
lv_obj_t * uic_pl_port3;
lv_obj_t * uic_lb_port2;
lv_obj_t * uic_pl_shade_2;
lv_obj_t * uic_pl_port2;
lv_obj_t * uic_lb_port1;
lv_obj_t * uic_pl_shade_1;
lv_obj_t * uic_pl_port1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_pl_port1 = NULL;
lv_obj_t * ui_pl_shade_1 = NULL;
lv_obj_t * ui_lb_port1 = NULL;
lv_obj_t * ui_pl_port2 = NULL;
lv_obj_t * ui_pl_shade_2 = NULL;
lv_obj_t * ui_lb_port2 = NULL;
lv_obj_t * ui_pl_port3 = NULL;
lv_obj_t * ui_pl_shade_3 = NULL;
lv_obj_t * ui_lb_port3 = NULL;
lv_obj_t * ui_pl_port4 = NULL;
lv_obj_t * ui_pl_shade_4 = NULL;
lv_obj_t * ui_lb_port4 = NULL;
lv_obj_t * ui_pl_volt = NULL;
lv_obj_t * ui_lb_tot_power = NULL;
lv_obj_t * ui_lb_volt = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pl_port1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pl_port1, 168);
    lv_obj_set_height(ui_pl_port1, 33);
    lv_obj_set_x(ui_pl_port1, 32);
    lv_obj_set_y(ui_pl_port1, -50);
    lv_obj_set_align(ui_pl_port1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pl_port1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pl_port1, lv_color_hex(0x00DC26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pl_port1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pl_port1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pl_port1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pl_shade_1 = lv_obj_create(ui_pl_port1);
    lv_obj_set_width(ui_pl_shade_1, 168);
    lv_obj_set_height(ui_pl_shade_1, 33);
    lv_obj_set_align(ui_pl_shade_1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pl_shade_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pl_shade_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pl_shade_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pl_shade_1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pl_shade_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pl_shade_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_port1 = lv_label_create(ui_pl_port1);
    lv_obj_set_width(ui_lb_port1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_port1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_port1, -1);
    lv_obj_set_y(ui_lb_port1, 2);
    lv_obj_set_align(ui_lb_port1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lb_port1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_lb_port1, "0000mA 0000mW");
    lv_label_set_recolor(ui_lb_port1, "true");
    lv_obj_set_style_text_color(ui_lb_port1, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_port1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_port1, &ui_font_xlm_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lb_port1, lv_color_hex(0xA9A9A9), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_lb_port1, 255, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_color(ui_lb_port1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_lb_port1, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_pl_port2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pl_port2, 168);
    lv_obj_set_height(ui_pl_port2, 33);
    lv_obj_set_x(ui_pl_port2, 32);
    lv_obj_set_y(ui_pl_port2, -17);
    lv_obj_set_align(ui_pl_port2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pl_port2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pl_port2, lv_color_hex(0x4FD3EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pl_port2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pl_port2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pl_port2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pl_port2, lv_color_hex(0xA9A9A9), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_pl_port2, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_pl_shade_2 = lv_obj_create(ui_pl_port2);
    lv_obj_set_width(ui_pl_shade_2, 168);
    lv_obj_set_height(ui_pl_shade_2, 33);
    lv_obj_set_align(ui_pl_shade_2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pl_shade_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pl_shade_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pl_shade_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pl_shade_2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pl_shade_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pl_shade_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_port2 = lv_label_create(ui_pl_port2);
    lv_obj_set_width(ui_lb_port2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_port2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_port2, 0);
    lv_obj_set_y(ui_lb_port2, 2);
    lv_obj_set_align(ui_lb_port2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lb_port2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_lb_port2, "0000mA 0000mW");
    lv_label_set_recolor(ui_lb_port2, "true");
    lv_obj_set_style_text_color(ui_lb_port2, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_port2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_port2, &ui_font_xlm_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pl_port3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pl_port3, 168);
    lv_obj_set_height(ui_pl_port3, 33);
    lv_obj_set_x(ui_pl_port3, 32);
    lv_obj_set_y(ui_pl_port3, 16);
    lv_obj_set_align(ui_pl_port3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pl_port3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pl_port3, lv_color_hex(0xF05959), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pl_port3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pl_port3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pl_port3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pl_port3, lv_color_hex(0xA9A9A9), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_pl_port3, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_pl_shade_3 = lv_obj_create(ui_pl_port3);
    lv_obj_set_width(ui_pl_shade_3, 168);
    lv_obj_set_height(ui_pl_shade_3, 33);
    lv_obj_set_align(ui_pl_shade_3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pl_shade_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pl_shade_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pl_shade_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pl_shade_3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pl_shade_3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pl_shade_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_port3 = lv_label_create(ui_pl_port3);
    lv_obj_set_width(ui_lb_port3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_port3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_port3, 0);
    lv_obj_set_y(ui_lb_port3, 2);
    lv_obj_set_align(ui_lb_port3, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lb_port3, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_lb_port3, "0000mA 0000mW");
    lv_label_set_recolor(ui_lb_port3, "true");
    lv_obj_set_style_text_color(ui_lb_port3, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_port3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_port3, &ui_font_xlm_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pl_port4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pl_port4, 168);
    lv_obj_set_height(ui_pl_port4, 33);
    lv_obj_set_x(ui_pl_port4, 32);
    lv_obj_set_y(ui_pl_port4, 49);
    lv_obj_set_align(ui_pl_port4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pl_port4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pl_port4, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pl_port4, lv_color_hex(0xF5D137), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pl_port4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pl_port4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pl_port4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pl_port4, lv_color_hex(0xA9A9A9), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_pl_port4, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_pl_shade_4 = lv_obj_create(ui_pl_port4);
    lv_obj_set_width(ui_pl_shade_4, 168);
    lv_obj_set_height(ui_pl_shade_4, 33);
    lv_obj_set_align(ui_pl_shade_4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pl_shade_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_pl_shade_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pl_shade_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pl_shade_4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pl_shade_4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pl_shade_4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_port4 = lv_label_create(ui_pl_port4);
    lv_obj_set_width(ui_lb_port4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_port4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_port4, 0);
    lv_obj_set_y(ui_lb_port4, 2);
    lv_obj_set_align(ui_lb_port4, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lb_port4, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_lb_port4, "0000mA 0000mW");
    lv_label_set_recolor(ui_lb_port4, "true");
    lv_obj_set_style_text_color(ui_lb_port4, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_port4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_port4, &ui_font_xlm_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pl_volt = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_pl_volt, 128);
    lv_obj_set_height(ui_pl_volt, 60);
    lv_obj_set_x(ui_pl_volt, 8);
    lv_obj_set_y(ui_pl_volt, -34);
    lv_obj_set_align(ui_pl_volt, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pl_volt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pl_volt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pl_volt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pl_volt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pl_volt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_pl_volt, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_tot_power = lv_label_create(ui_pl_volt);
    lv_obj_set_width(ui_lb_tot_power, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_tot_power, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_tot_power, 0);
    lv_obj_set_y(ui_lb_tot_power, 14);
    lv_obj_set_align(ui_lb_tot_power, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lb_tot_power, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_lb_tot_power, "00.000 W");
    lv_obj_set_style_text_color(ui_lb_tot_power, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_tot_power, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_tot_power, &ui_font_lcd_mono_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lb_tot_power, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lb_volt = lv_label_create(ui_pl_volt);
    lv_obj_set_width(ui_lb_volt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lb_volt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lb_volt, 0);
    lv_obj_set_y(ui_lb_volt, -14);
    lv_obj_set_align(ui_lb_volt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lb_volt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_lb_volt, "00.000 V");
    lv_obj_set_style_text_color(ui_lb_volt, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lb_volt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lb_volt, &ui_font_lcd_mono_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(ui_lb_volt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_pl_port1 = ui_pl_port1;
    uic_pl_shade_1 = ui_pl_shade_1;
    uic_lb_port1 = ui_lb_port1;
    uic_pl_port2 = ui_pl_port2;
    uic_pl_shade_2 = ui_pl_shade_2;
    uic_lb_port2 = ui_lb_port2;
    uic_pl_port3 = ui_pl_port3;
    uic_pl_shade_3 = ui_pl_shade_3;
    uic_lb_port3 = ui_lb_port3;
    uic_pl_port4 = ui_pl_port4;
    uic_pl_shade_4 = ui_pl_shade_4;
    uic_lb_port4 = ui_lb_port4;
    uic_pl_volt = ui_pl_volt;
    uic_lb_tot_power = ui_lb_tot_power;
    uic_lb_volt = ui_lb_volt;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_pl_port1 = NULL;
    ui_pl_port1 = NULL;
    uic_pl_shade_1 = NULL;
    ui_pl_shade_1 = NULL;
    uic_lb_port1 = NULL;
    ui_lb_port1 = NULL;
    uic_pl_port2 = NULL;
    ui_pl_port2 = NULL;
    uic_pl_shade_2 = NULL;
    ui_pl_shade_2 = NULL;
    uic_lb_port2 = NULL;
    ui_lb_port2 = NULL;
    uic_pl_port3 = NULL;
    ui_pl_port3 = NULL;
    uic_pl_shade_3 = NULL;
    ui_pl_shade_3 = NULL;
    uic_lb_port3 = NULL;
    ui_lb_port3 = NULL;
    uic_pl_port4 = NULL;
    ui_pl_port4 = NULL;
    uic_pl_shade_4 = NULL;
    ui_pl_shade_4 = NULL;
    uic_lb_port4 = NULL;
    ui_lb_port4 = NULL;
    uic_pl_volt = NULL;
    ui_pl_volt = NULL;
    uic_lb_tot_power = NULL;
    ui_lb_tot_power = NULL;
    uic_lb_volt = NULL;
    ui_lb_volt = NULL;

}
