// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: CH335F_USB_HUB

#ifndef _CH335F_USB_HUB_UI_H
#define _CH335F_USB_HUB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * plenable_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * plfromleft_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * pldisable_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_lcd_mono_30);
LV_FONT_DECLARE(ui_font_xlm_42);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
