// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: CH335F_USB_HUB

#ifndef _CH335F_USB_HUB_UI_H
#define _CH335F_USB_HUB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void plenable_Animation(lv_obj_t * TargetObject, int delay);
void plfromleft_Animation(lv_obj_t * TargetObject, int delay);
void pldisable_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_pl_port1;
extern lv_obj_t * ui_pl_shade_1;
extern lv_obj_t * ui_lb_port1;
extern lv_obj_t * ui_pl_port2;
extern lv_obj_t * ui_pl_shade_2;
extern lv_obj_t * ui_lb_port2;
extern lv_obj_t * ui_pl_port3;
extern lv_obj_t * ui_pl_shade_3;
extern lv_obj_t * ui_lb_port3;
extern lv_obj_t * ui_pl_port4;
extern lv_obj_t * ui_pl_shade_4;
extern lv_obj_t * ui_lb_port4;
extern lv_obj_t * ui_pl_volt;
extern lv_obj_t * ui_lb_tot_power;
extern lv_obj_t * ui_lb_volt;
// CUSTOM VARIABLES
extern lv_obj_t * uic_pl_port1;
extern lv_obj_t * uic_pl_shade_1;
extern lv_obj_t * uic_lb_port1;
extern lv_obj_t * uic_pl_port2;
extern lv_obj_t * uic_pl_shade_2;
extern lv_obj_t * uic_lb_port2;
extern lv_obj_t * uic_pl_port3;
extern lv_obj_t * uic_pl_shade_3;
extern lv_obj_t * uic_lb_port3;
extern lv_obj_t * uic_pl_port4;
extern lv_obj_t * uic_pl_shade_4;
extern lv_obj_t * uic_lb_port4;
extern lv_obj_t * uic_pl_volt;
extern lv_obj_t * uic_lb_tot_power;
extern lv_obj_t * uic_lb_volt;

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_lcd_mono_30);
LV_FONT_DECLARE(ui_font_xlm_42);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
