// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: CH335F_USB_HUB

#include "ui.h"

void backlight_on_cb(lv_event_t * e)
{
	// Your code here
}
